const AUX_CONFIG = {
    LAUNCH_INVALID_SELECTOR_ERROR: true,
    LAUNCH_ELEMENT_NOT_FOUND_ERROR: true,
    LAUNCH_TYPE_ERROR: true,
    LAUNCH_VOID_OBJECT_ERROR: true,
    LAUNCH_EXPECTED_PROPERTY_ERROR: true,
}

export {AUX_CONFIG as __}